name: Build and Release JAR

on:
  release:
    types:
      - created


jobs:
  build:
    name: Build and Release JAR
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/wortschatzhelper-1.0-SNAPSHOT.jar
        asset_name: wortschatzhelper-1.0-SNAPSHOT.jar
        asset_content_type: application/java-archive
